### ISSUE TITLE
 Implement Weather Dashboard Backend

### ISSUE THREAD

**Issue by mirasoldavila13** [mirasoldavila13/Weather-Dashboard#1]
## User Story:

AS A traveler
I WANT TO see the weather outlook for multiple cities
SO THAT I can plan a trip accordingly

## Acceptance Criteria:

1. The backend should connect the frontend with the OpenWeather API to retrieve weather data.
2. Cities should be saved with a unique ID in the searchHistory.json file.
3. The application must be deployed to Render.

## Tasks:

- [ ] Implement API call to OpenWeather API to retrieve weather data.
- [ ] Store cities with unique IDs in searchHistory.json.
- [ ] Set up deployment to Render.
