### ISSUE TITLE
Search and Display Current Weather Conditions

### ISSUE THREAD

**Issue by mirasoldavila13** [mirasoldavila13/Weather-Dashboard#2]
## User Story:

AS A traveler
I WANT TO view current weather conditions for a searched city
SO THAT I can plan my activities for the day

## Acceptance Criteria:

1. WHEN a city is searched, THEN the city name, date, weather icon, description, temperature, humidity, and wind speed should be displayed.
2. The search history should update with the searched city.

## Tasks:

- [ ] Implement search functionality to input city name.
- [ ] Fetch and display current weather data for the searched city.
- [ ] Update search history with the searched city.
