### ISSUE TITLE
Search History Functionality

### ISSUE THREAD

**Issue by mirasoldavila13** [mirasoldavila13/Weather-Dashboard#4]
## User Story:

AS A traveler
I WANT TO select a city from my search history
SO THAT I can quickly view its weather data again

## Acceptance Criteria:

1.  Cities should be saved in the searchHistory.json file with a unique ID.
2. WHEN a city is clicked in the search history, THEN the current and future weather conditions for that city should be displayed.

## Tasks:

- [ ]  Implement saving cities to searchHistory.json with a unique ID.
- [ ]  Display cities in search history on the frontend.
- [ ]  Implement functionality to display weather data for a city when clicked in the search history.
